import Lake
open Lake DSL

-- The Aeneas Lean library (provides `import Aeneas`, the Result/ControlFlow
-- monad, integer types, loop combinators, and the step/progress/grind tactics).
-- It transitively requires mathlib @ the pinned tag in its own lakefile.
-- Path points at the local Charon/Aeneas clone set up per ../aeneas-setup-log.txt.
require aeneas from "/home/user/aeneas-toolchain/aeneas/backends/lean"

package «verification» where

-- `Smoke` is generated by Aeneas from verification/examples/smoke.rs.
-- Regenerate with the commands in ../aeneas-setup-log.txt / ../README.md.
lean_lib «Smoke» where

-- Hand-written specs/proofs over the generated model (imports `Smoke`).
@[default_target] lean_lib «SmokeProofs» where
