-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [smoke]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace smoke

/-- [smoke::add]:
    Source: 'smoke.rs', lines 5:0-7:1
    Visibility: public -/
def add (x : Std.U32) (y : Std.U32) : Result Std.U32 := do
  x + y

/-- [smoke::factorial]:
    Source: 'smoke.rs', lines 9:0-15:1
    Visibility: public -/
def factorial (n : Std.U64) : Result Std.U64 := do
  if n = 0#u64
  then ok 1#u64
  else let i ← n - 1#u64
       let i1 ← factorial i
       n * i1
partial_fixpoint

/-- [smoke::sum_slice]: loop body 0:
    Source: 'smoke.rs', lines 20:4-23:5
    Visibility: public -/
@[rust_loop_body]
def sum_slice_loop.body
  (xs : Slice Std.U32) (total : Std.U32) (i : Std.Usize) :
  Result (ControlFlow (Std.U32 × Std.Usize) Std.U32)
  := do
  let i1 := Slice.len xs
  if i < i1
  then
    let i2 ← Slice.index_usize xs i
    let total1 ← total + i2
    let i3 ← i + 1#usize
    ok (cont (total1, i3))
  else ok (done total)

/-- [smoke::sum_slice]: loop 0:
    Source: 'smoke.rs', lines 20:4-23:5
    Visibility: public -/
@[rust_loop]
def sum_slice_loop
  (xs : Slice Std.U32) (total : Std.U32) (i : Std.Usize) : Result Std.U32 := do
  loop
    (fun (total1, i1) => sum_slice_loop.body xs total1 i1)
    (total, i)

/-- [smoke::sum_slice]:
    Source: 'smoke.rs', lines 17:0-25:1
    Visibility: public -/
@[reducible]
def sum_slice (xs : Slice Std.U32) : Result Std.U32 := do
  sum_slice_loop xs 0#u32 0#usize

end smoke
